services:
  
  auth_service:
    build: ./auth_service  
    container_name: auth_service  
    ports:
      - "8000:8000"  
    volumes:
      - ./auth_service:/app  
    env_file:
      - ./auth_service/.env  
    depends_on:
      - redis  
    restart: always  
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      
  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
